// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// DBPathRequest defines model for DBPathRequest.
type DBPathRequest struct {
	Path *string `json:"path,omitempty"`
}

// DBPathResponse defines model for DBPathResponse.
type DBPathResponse struct {
	Path *string `json:"path,omitempty"`
}

// LogLevelRequest defines model for LogLevelRequest.
type LogLevelRequest struct {
	Level *string `json:"level,omitempty"`
}

// PRWaitState defines model for PRWaitState.
type PRWaitState struct {
	EndedAt    *time.Time `json:"endedAt,omitempty"`
	Error      *string    `json:"error,omitempty"`
	HeadBranch *string    `json:"headBranch,omitempty"`
	HtmlUrl    *string    `json:"htmlUrl,omitempty"`
	Name       *string    `json:"name,omitempty"`
	Owner      *string    `json:"owner,omitempty"`
	PrNumber   *int       `json:"prNumber,omitempty"`
	Repo       *string    `json:"repo,omitempty"`
	StartedAt  *time.Time `json:"startedAt,omitempty"`
	Status     *string    `json:"status,omitempty"`
	Title      *string    `json:"title,omitempty"`
	WaitFor    *string    `json:"waitFor,omitempty"`
}

// ParallelGroupState defines model for ParallelGroupState.
type ParallelGroupState struct {
	Name   *string      `json:"name,omitempty"`
	Status *string      `json:"status,omitempty"`
	Steps  *[]StepState `json:"steps,omitempty"`
}

// RunRequest defines model for RunRequest.
type RunRequest struct {
	Inputs      *map[string]string `json:"inputs,omitempty"`
	SkipPRCheck *bool              `json:"skipPRCheck,omitempty"`
	Workflow    *string            `json:"workflow,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Running  *bool          `json:"running,omitempty"`
	Workflow *WorkflowState `json:"workflow,omitempty"`
}

// StepState defines model for StepState.
type StepState struct {
	BuildUrl *string `json:"buildUrl,omitempty"`
	Error    *string `json:"error,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Job      *string `json:"job,omitempty"`
	Name     *string `json:"name,omitempty"`
	Result   *string `json:"result,omitempty"`
	Status   *string `json:"status,omitempty"`
}

// WorkflowInfo defines model for WorkflowInfo.
type WorkflowInfo struct {
	Error *string `json:"error,omitempty"`
	Name  *string `json:"name,omitempty"`
	Path  *string `json:"path,omitempty"`
	Valid *bool   `json:"valid,omitempty"`
}

// WorkflowItemState defines model for WorkflowItemState.
type WorkflowItemState struct {
	IsPRWait   *bool               `json:"isPRWait,omitempty"`
	IsParallel *bool               `json:"isParallel,omitempty"`
	Parallel   *ParallelGroupState `json:"parallel,omitempty"`
	PrWait     *PRWaitState        `json:"prWait,omitempty"`
	Step       *StepState          `json:"step,omitempty"`
}

// WorkflowRun defines model for WorkflowRun.
type WorkflowRun struct {
	ConfigSnapshot *string            `json:"config_snapshot,omitempty"`
	EndTime        *time.Time         `json:"end_time,omitempty"`
	Id             *int64             `json:"id,omitempty"`
	Inputs         *map[string]string `json:"inputs,omitempty"`
	SkipPrCheck    *bool              `json:"skip_pr_check,omitempty"`
	StartTime      *time.Time         `json:"start_time,omitempty"`
	Status         *string            `json:"status,omitempty"`
	WorkflowName   *string            `json:"workflow_name,omitempty"`
	WorkflowPath   *string            `json:"workflow_path,omitempty"`
}

// WorkflowState defines model for WorkflowState.
type WorkflowState struct {
	Inputs *map[string]string   `json:"inputs,omitempty"`
	Items  *[]WorkflowItemState `json:"items,omitempty"`
	Name   *string              `json:"name,omitempty"`
	Status *string              `json:"status,omitempty"`
}

// GetHistoryParams defines parameters for GetHistory.
type GetHistoryParams struct {
	// Limit Maximum number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// WorkflowPath Filter by workflow path
	WorkflowPath *string `form:"workflow_path,omitempty" json:"workflow_path,omitempty"`

	// Status Filter by status (running, success, failed, stopped)
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// RunWorkflowJSONRequestBody defines body for RunWorkflow for application/json ContentType.
type RunWorkflowJSONRequestBody = RunRequest

// SetDBPathJSONRequestBody defines body for SetDBPath for application/json ContentType.
type SetDBPathJSONRequestBody = DBPathRequest

// SetLogLevelJSONRequestBody defines body for SetLogLevel for application/json ContentType.
type SetLogLevelJSONRequestBody = LogLevelRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List workflow run history
	// (GET /api/history)
	GetHistory(w http.ResponseWriter, r *http.Request, params GetHistoryParams)
	// Get specific workflow run details
	// (GET /api/history/{id})
	GetHistoryRun(w http.ResponseWriter, r *http.Request, id int)
	// Start a workflow
	// (POST /api/run)
	RunWorkflow(w http.ResponseWriter, r *http.Request)
	// Get current database path
	// (GET /api/settings/db-path)
	GetDBPath(w http.ResponseWriter, r *http.Request)
	// Update database path
	// (PUT /api/settings/db-path)
	SetDBPath(w http.ResponseWriter, r *http.Request)
	// Get current log level
	// (GET /api/settings/log-level)
	GetLogLevel(w http.ResponseWriter, r *http.Request)
	// Set log level
	// (POST /api/settings/log-level)
	SetLogLevel(w http.ResponseWriter, r *http.Request)
	// Get current workflow status
	// (GET /api/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// Stop the running workflow
	// (POST /api/stop)
	StopWorkflow(w http.ResponseWriter, r *http.Request)
	// List available workflows
	// (GET /api/workflows)
	ListWorkflows(w http.ResponseWriter, r *http.Request)
	// Get workflow definition
	// (GET /api/workflows/{name}/definition)
	GetWorkflowDefinition(w http.ResponseWriter, r *http.Request, name string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List workflow run history
// (GET /api/history)
func (_ Unimplemented) GetHistory(w http.ResponseWriter, r *http.Request, params GetHistoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get specific workflow run details
// (GET /api/history/{id})
func (_ Unimplemented) GetHistoryRun(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a workflow
// (POST /api/run)
func (_ Unimplemented) RunWorkflow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current database path
// (GET /api/settings/db-path)
func (_ Unimplemented) GetDBPath(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update database path
// (PUT /api/settings/db-path)
func (_ Unimplemented) SetDBPath(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current log level
// (GET /api/settings/log-level)
func (_ Unimplemented) GetLogLevel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set log level
// (POST /api/settings/log-level)
func (_ Unimplemented) SetLogLevel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current workflow status
// (GET /api/status)
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop the running workflow
// (POST /api/stop)
func (_ Unimplemented) StopWorkflow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List available workflows
// (GET /api/workflows)
func (_ Unimplemented) ListWorkflows(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get workflow definition
// (GET /api/workflows/{name}/definition)
func (_ Unimplemented) GetWorkflowDefinition(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHistory operation middleware
func (siw *ServerInterfaceWrapper) GetHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "workflow_path" -------------

	err = runtime.BindQueryParameter("form", true, false, "workflow_path", r.URL.Query(), &params.WorkflowPath)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workflow_path", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHistoryRun operation middleware
func (siw *ServerInterfaceWrapper) GetHistoryRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHistoryRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunWorkflow operation middleware
func (siw *ServerInterfaceWrapper) RunWorkflow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunWorkflow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDBPath operation middleware
func (siw *ServerInterfaceWrapper) GetDBPath(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDBPath(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetDBPath operation middleware
func (siw *ServerInterfaceWrapper) SetDBPath(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetDBPath(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) GetLogLevel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogLevel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) SetLogLevel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetLogLevel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopWorkflow operation middleware
func (siw *ServerInterfaceWrapper) StopWorkflow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopWorkflow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkflows operation middleware
func (siw *ServerInterfaceWrapper) ListWorkflows(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkflows(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflowDefinition operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflowDefinition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflowDefinition(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/history", wrapper.GetHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/history/{id}", wrapper.GetHistoryRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/run", wrapper.RunWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/settings/db-path", wrapper.GetDBPath)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/settings/db-path", wrapper.SetDBPath)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/settings/log-level", wrapper.GetLogLevel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/settings/log-level", wrapper.SetLogLevel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/status", wrapper.GetStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/stop", wrapper.StopWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/workflows", wrapper.ListWorkflows)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/workflows/{name}/definition", wrapper.GetWorkflowDefinition)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYXW/bNhT9KwS3hw1Q62xrB8xvaYN2GbIuiFHkYSgCWryy2VAkS17FCwL/94GUZOuD",
	"dOzEGfYUR7zivTzn3A/xgea6NFqBQkenD9TlSyhZ+Hn27pLh8gq+VeDQPzBWG7AoICwbhkv/F+8N0Cl1",
	"aIVa0PU6a5/o+VfIka6zzU7OaOXgWVtd6MUF3IFMhiX96p6bXV5dM4EzZBgJChQHfho8FNqWDOmUcobw",
	"CkUJNBvun1GwVtuI54wugfF3lql8GV/GUn62MrqmWAnRBb1SEPdm7KeqnPcWhUJYgPWrFoyOvuaQWTzs",
	"xA4ZVi66GwqU8cBXTOCHKFBRiphlUoL8aHVlEkwlMdoRn0MwYUUglOHH9xYKOqXfTbYJMWmyYTJDaJxv",
	"Y2TWsvt40FeVSupTKFPVqcY4Fyi0YvKyZzHGcri/uxXm8ur9EvLbzgtzrSUwFTDW9raQerUnyLOAUzo/",
	"baWUf/lRX7swvG7sGhzjcUCK43klJE8lSTrzhHLIVB6Xx1c9PyznLLhK4mFSi52zheJcFTpSeJKnSQaW",
	"KKAZvWNS8BhvO8NCKBM0CFfXzLgUhGvTNb5uOqu7pBJJ+lDXWs873+3U9CbPD8juXbBcVWoMSK5VIRY3",
	"TjHjljquDVD8JpTQvQtrzdnGVij89c3WrlPNj1VNboy9ydP1JPSGA8+wo/i2JeMmKeiNxQGjQb/AvEjh",
	"3TSLvbrGOJ9G3SN7QvMaB7YOSqhrCQeXW2H8+eiUnl6ek0Jb8geoW6Ec+SD1ipwxt5xrZjnd9GnaMzi9",
	"PKcZvQPr6l1+en3y+iQMHQYUM4JO6S/hUV15QpATZsRkKRxqe+//X0BIBo8v88GcczqlHwF/b0zqalAC",
	"gnV0+vcw8D/ZP6KsSqLCKEN0Qeri6whqYgErq6g/NJ3SbxWE/WokqRSlQJo1k2wNScFC3X57Ms6hdTZ0",
	"/VdROMAAm2ELoUL4CWc62Ma97eXsg5AIlszvSSt5EiQfd9dPi67XkUbSjmphkR+arp4RV+U5OJeRggkJ",
	"PCMOtTHAf0xE0Shzl/svoVmGcSKo4+eTk6ZaIqggDGaMFHnAdvLVabX9+Dg4v3xhHs9l62yAwIVw6IW0",
	"AdpWyvkX39bB9a1nYO/AkroZ+81cVZbMa7veqLsLaXXv7bqJMHkQfL1HNvgTPJIQ111/52ctNY0QGmaE",
	"T2kL3yphgdMp2goiLG3l+Fya9mZnzEbvPByQCRnIeHPyZkxGz1hpn5yV4k/h7iMgcQZyUYi8z+EmhpZD",
	"2/R77SLcXVWqDaqBHBy+0/z+aPh1PiICfH1a189krt8bD+w1CXKaL8iaxQgt5yqMo8S2x/J2v+1gm0kL",
	"jN+T9vujT+XMuyNsw+KWOQeIQi3chM9ftQNEKgPruwn6gokwuP2IIPi+shYUEs6QzZmDugU8Ud15ajNT",
	"RRCY9RA4vor7l0gvIOTnIX/WBYlUxk+0Bwn4UIY+BxdDckbClXrxanOTlZJuexdGj1oL9r9ASwtZ6gWp",
	"90nrs2OTJYrsbHDG48tzeJ344pX2OehetIgRP3M+JtIUBzMY8lNLb9MCUnKbtWPfi+Xr4B5qh8CaaNPq",
	"WnWaUmvZnFObdFufoTa9vv6/a7FhMk8OSp90b6iJdk1tCC6hXY60z/ZJWg1+Ar7eWP2Xs364Mttj2D8l",
	"cjDuu9gUz+6YkGwuYWDWx2Hy4Ofr9YRDIZSoPaTzpA31bGv9yGwPKtcceN2EtCXemw/d07TaqjEy8Ic/",
	"e4z8R/swO+SGNy3jDpCPjvydcX+U7avYhsEsdOAa68pKOqUTuv6y/jcAAP//QLCRxu4aAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
