// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// LogLevelRequest defines model for LogLevelRequest.
type LogLevelRequest struct {
	Level *string `json:"level,omitempty"`
}

// PRWaitState defines model for PRWaitState.
type PRWaitState struct {
	HeadBranch *string `json:"headBranch,omitempty"`
	HtmlUrl    *string `json:"htmlUrl,omitempty"`
	Name       *string `json:"name,omitempty"`
	Owner      *string `json:"owner,omitempty"`
	PrNumber   *int    `json:"prNumber,omitempty"`
	Repo       *string `json:"repo,omitempty"`
	Status     *string `json:"status,omitempty"`
	Title      *string `json:"title,omitempty"`
	WaitFor    *string `json:"waitFor,omitempty"`
}

// ParallelGroupState defines model for ParallelGroupState.
type ParallelGroupState struct {
	Name   *string      `json:"name,omitempty"`
	Status *string      `json:"status,omitempty"`
	Steps  *[]StepState `json:"steps,omitempty"`
}

// RunRequest defines model for RunRequest.
type RunRequest struct {
	SkipPRCheck *bool   `json:"skipPRCheck,omitempty"`
	Workflow    *string `json:"workflow,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Running  *bool          `json:"running,omitempty"`
	Workflow *WorkflowState `json:"workflow,omitempty"`
}

// StepState defines model for StepState.
type StepState struct {
	BuildUrl *string `json:"buildUrl,omitempty"`
	Error    *string `json:"error,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Job      *string `json:"job,omitempty"`
	Name     *string `json:"name,omitempty"`
	Result   *string `json:"result,omitempty"`
	Status   *string `json:"status,omitempty"`
}

// WorkflowInfo defines model for WorkflowInfo.
type WorkflowInfo struct {
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

// WorkflowItemState defines model for WorkflowItemState.
type WorkflowItemState struct {
	IsPRWait   *bool               `json:"isPRWait,omitempty"`
	IsParallel *bool               `json:"isParallel,omitempty"`
	Parallel   *ParallelGroupState `json:"parallel,omitempty"`
	PrWait     *PRWaitState        `json:"prWait,omitempty"`
	Step       *StepState          `json:"step,omitempty"`
}

// WorkflowState defines model for WorkflowState.
type WorkflowState struct {
	Items  *[]WorkflowItemState `json:"items,omitempty"`
	Name   *string              `json:"name,omitempty"`
	Status *string              `json:"status,omitempty"`
}

// RunWorkflowJSONRequestBody defines body for RunWorkflow for application/json ContentType.
type RunWorkflowJSONRequestBody = RunRequest

// SetLogLevelJSONRequestBody defines body for SetLogLevel for application/json ContentType.
type SetLogLevelJSONRequestBody = LogLevelRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start a workflow
	// (POST /api/run)
	RunWorkflow(w http.ResponseWriter, r *http.Request)
	// Get current log level
	// (GET /api/settings/log-level)
	GetLogLevel(w http.ResponseWriter, r *http.Request)
	// Set log level
	// (POST /api/settings/log-level)
	SetLogLevel(w http.ResponseWriter, r *http.Request)
	// Get current workflow status
	// (GET /api/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// Stop the running workflow
	// (POST /api/stop)
	StopWorkflow(w http.ResponseWriter, r *http.Request)
	// List available workflows
	// (GET /api/workflows)
	ListWorkflows(w http.ResponseWriter, r *http.Request)
	// Get workflow definition
	// (GET /api/workflows/{name}/definition)
	GetWorkflowDefinition(w http.ResponseWriter, r *http.Request, name string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Start a workflow
// (POST /api/run)
func (_ Unimplemented) RunWorkflow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current log level
// (GET /api/settings/log-level)
func (_ Unimplemented) GetLogLevel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set log level
// (POST /api/settings/log-level)
func (_ Unimplemented) SetLogLevel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current workflow status
// (GET /api/status)
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop the running workflow
// (POST /api/stop)
func (_ Unimplemented) StopWorkflow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List available workflows
// (GET /api/workflows)
func (_ Unimplemented) ListWorkflows(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get workflow definition
// (GET /api/workflows/{name}/definition)
func (_ Unimplemented) GetWorkflowDefinition(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RunWorkflow operation middleware
func (siw *ServerInterfaceWrapper) RunWorkflow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunWorkflow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) GetLogLevel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogLevel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) SetLogLevel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetLogLevel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopWorkflow operation middleware
func (siw *ServerInterfaceWrapper) StopWorkflow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopWorkflow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkflows operation middleware
func (siw *ServerInterfaceWrapper) ListWorkflows(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkflows(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflowDefinition operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflowDefinition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflowDefinition(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/run", wrapper.RunWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/settings/log-level", wrapper.GetLogLevel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/settings/log-level", wrapper.SetLogLevel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/status", wrapper.GetStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/stop", wrapper.StopWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/workflows", wrapper.ListWorkflows)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/workflows/{name}/definition", wrapper.GetWorkflowDefinition)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXTY/jNgz9K4LaY7qetntpbvuBHaQYLAYJijkUe1BsJtGMLKoUnSAY5L8XkqN82HJm",
	"0tkFeoph0iL5+PjEPMsSa4cWLHs5fpa+XEGt4uMdLu9gDWYK/zTgObxyhA6INUQHE6zhgbcO5Fh6Jm2X",
	"crcbpTc4f4SS5W4k76cPSvOMFUP/oBWo6iMpW64yp43kimvzF5mszaoasgbcWKCsxdHXpp6fGbVlWAIF",
	"K4HD7GeeFTc+a2LNJp/FRmn+gvRakBQpY8DcEjZuAKvBgi/k5xlctGiGOj78TLCQY/lTcex+sW99MWPY",
	"Bz/mqIjUNp/0tLGDDPFP2t1PP62gfDpJbI5oQNmID9LTwuDmlQDNYo1T8A6tz4BDjbXh4xdjXar/Ye+3",
	"xyCfBwz1Z95oUw2xFYgwT0ptPStb5lv7iPPryE/gG8PX0SRXZ4JiYhd4BRWd4tW1ERjqAUS1b8Uj31Xt",
	"09Tk7e7EeqnrmdmLWpEiX/z2RNz243bFkF2CZQiSNMevGug+xr3BHv0HXennvYtEbqlSgS9JO9Zo5Vh+",
	"uJ+IBZL4E+yTtl58MbgRn5VfzVFRJQ8SKs8cPtxP5EiugXx7yq/vbt7dRHF3YJXTcix/j69aysUkC+V0",
	"QY2NoGErSgE6FTKZVHIcBCshIsOoRO36iNU2uJZoGWz8SjlndBm/Kx492uP1+BLgJ5IYMQkxNEElx0wN",
	"tPMZFSxm/NvNzVWROxJ7XXvO25JwEJ4VMVQB2/dtOueOE7tWRleCUlnB74++3+FAZQhUtRVJkUNs39S1",
	"oq0cBx0nFkocJDmYY+c8MGu79IXB5S+HBWMJmT7eAqcVRX5XSF+/1/QR/dQQgWVhcCnac84rvwUWZd9n",
	"NMDVWafG78/V7pb3wwn7FnTvEmLCA79I1qEezKDbn5Z6h0kaolu7fryVbJevhbMF5wLB9tkOs2tzMtvJ",
	"c18numF1nDG6M3n83ykVOpeU6n2/+V/xWPmQ+KATvIJkzqhQejPMhjvt+eHg9UacrrvFwwXb38x7iH0Q",
	"RnsWuBDHas6BCDUItVbaqLmBjts5DsVz2A92RQULbXUbYXhOUqqfj97tIlYDA3k5/rvbNbAlVlCJcI0L",
	"JBGihdRDmzZHNurgG7fLtLC0P13FGp2A2yXbtx84vt2/DsM0PgFyiMkHX4ssFtjYKjPtm9yB0Q1onbBu",
	"wt8RWcjdt92/AQAA//+F5mAI8A8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
