// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// DBPathRequest defines model for DBPathRequest.
type DBPathRequest struct {
	Path *string `json:"path,omitempty"`
}

// DBPathResponse defines model for DBPathResponse.
type DBPathResponse struct {
	Path *string `json:"path,omitempty"`
}

// DisabledStep defines model for DisabledStep.
type DisabledStep struct {
	ItemIndex *int `json:"itemIndex,omitempty"`
	StepIndex *int `json:"stepIndex,omitempty"`
}

// LogLevelRequest defines model for LogLevelRequest.
type LogLevelRequest struct {
	Level *string `json:"level,omitempty"`
}

// PRWaitOverride defines model for PRWaitOverride.
type PRWaitOverride struct {
	HeadBranch *string `json:"headBranch,omitempty"`
	ItemIndex  *int    `json:"itemIndex,omitempty"`
	Owner      *string `json:"owner,omitempty"`
	PollSecs   *int    `json:"pollSecs,omitempty"`
	PrNumber   *int    `json:"prNumber,omitempty"`
	Repo       *string `json:"repo,omitempty"`
	WaitFor    *string `json:"waitFor,omitempty"`
}

// PRWaitState defines model for PRWaitState.
type PRWaitState struct {
	EndedAt    *time.Time `json:"endedAt,omitempty"`
	Error      *string    `json:"error,omitempty"`
	HeadBranch *string    `json:"headBranch,omitempty"`
	HtmlUrl    *string    `json:"htmlUrl,omitempty"`
	Name       *string    `json:"name,omitempty"`
	Owner      *string    `json:"owner,omitempty"`
	PrNumber   *int       `json:"prNumber,omitempty"`
	Repo       *string    `json:"repo,omitempty"`
	StartedAt  *time.Time `json:"startedAt,omitempty"`
	Status     *string    `json:"status,omitempty"`
	Title      *string    `json:"title,omitempty"`
	WaitFor    *string    `json:"waitFor,omitempty"`
}

// ParallelGroupState defines model for ParallelGroupState.
type ParallelGroupState struct {
	Name   *string      `json:"name,omitempty"`
	Status *string      `json:"status,omitempty"`
	Steps  *[]StepState `json:"steps,omitempty"`
}

// RunRequest defines model for RunRequest.
type RunRequest struct {
	DisabledSteps   *[]DisabledStep    `json:"disabledSteps,omitempty"`
	Inputs          *map[string]string `json:"inputs,omitempty"`
	PrWaitOverrides *[]PRWaitOverride  `json:"prWaitOverrides,omitempty"`
	Workflow        *string            `json:"workflow,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Running  *bool          `json:"running,omitempty"`
	Workflow *WorkflowState `json:"workflow,omitempty"`
}

// StepState defines model for StepState.
type StepState struct {
	// BuildNumber Jenkins build number captured after the job completes
	BuildNumber *int    `json:"buildNumber,omitempty"`
	BuildUrl    *string `json:"buildUrl,omitempty"`
	Error       *string `json:"error,omitempty"`
	Instance    *string `json:"instance,omitempty"`
	Job         *string `json:"job,omitempty"`
	Name        *string `json:"name,omitempty"`
	Result      *string `json:"result,omitempty"`
	Status      *string `json:"status,omitempty"`

	// UsedInputs Workflow inputs referenced by this step's params (key -> resolved value)
	UsedInputs *map[string]string `json:"usedInputs,omitempty"`
}

// WorkflowInfo defines model for WorkflowInfo.
type WorkflowInfo struct {
	Error *string `json:"error,omitempty"`
	Name  *string `json:"name,omitempty"`
	Path  *string `json:"path,omitempty"`
	Valid *bool   `json:"valid,omitempty"`
}

// WorkflowItemState defines model for WorkflowItemState.
type WorkflowItemState struct {
	IsPRWait   *bool               `json:"isPRWait,omitempty"`
	IsParallel *bool               `json:"isParallel,omitempty"`
	Parallel   *ParallelGroupState `json:"parallel,omitempty"`
	PrWait     *PRWaitState        `json:"prWait,omitempty"`
	Step       *StepState          `json:"step,omitempty"`
}

// WorkflowRun defines model for WorkflowRun.
type WorkflowRun struct {
	ConfigSnapshot *string            `json:"config_snapshot,omitempty"`
	EndTime        *time.Time         `json:"end_time,omitempty"`
	Id             *int64             `json:"id,omitempty"`
	Inputs         *map[string]string `json:"inputs,omitempty"`
	StartTime      *time.Time         `json:"start_time,omitempty"`
	Status         *string            `json:"status,omitempty"`
	WorkflowName   *string            `json:"workflow_name,omitempty"`
	WorkflowPath   *string            `json:"workflow_path,omitempty"`
}

// WorkflowState defines model for WorkflowState.
type WorkflowState struct {
	Inputs *map[string]string   `json:"inputs,omitempty"`
	Items  *[]WorkflowItemState `json:"items,omitempty"`
	Name   *string              `json:"name,omitempty"`
	Status *string              `json:"status,omitempty"`
}

// GetHistoryParams defines parameters for GetHistory.
type GetHistoryParams struct {
	// Limit Maximum number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// WorkflowPath Filter by workflow path
	WorkflowPath *string `form:"workflow_path,omitempty" json:"workflow_path,omitempty"`

	// Status Filter by status (running, success, failed, stopped)
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// RunWorkflowJSONRequestBody defines body for RunWorkflow for application/json ContentType.
type RunWorkflowJSONRequestBody = RunRequest

// SetDBPathJSONRequestBody defines body for SetDBPath for application/json ContentType.
type SetDBPathJSONRequestBody = DBPathRequest

// SetLogLevelJSONRequestBody defines body for SetLogLevel for application/json ContentType.
type SetLogLevelJSONRequestBody = LogLevelRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List workflow run history
	// (GET /api/history)
	GetHistory(w http.ResponseWriter, r *http.Request, params GetHistoryParams)
	// Get specific workflow run details
	// (GET /api/history/{id})
	GetHistoryRun(w http.ResponseWriter, r *http.Request, id int)
	// Start a workflow
	// (POST /api/run)
	RunWorkflow(w http.ResponseWriter, r *http.Request)
	// Get current database path
	// (GET /api/settings/db-path)
	GetDBPath(w http.ResponseWriter, r *http.Request)
	// Update database path
	// (PUT /api/settings/db-path)
	SetDBPath(w http.ResponseWriter, r *http.Request)
	// Get current log level
	// (GET /api/settings/log-level)
	GetLogLevel(w http.ResponseWriter, r *http.Request)
	// Set log level
	// (POST /api/settings/log-level)
	SetLogLevel(w http.ResponseWriter, r *http.Request)
	// Get current workflow status
	// (GET /api/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// Stop the running workflow
	// (POST /api/stop)
	StopWorkflow(w http.ResponseWriter, r *http.Request)
	// List available workflows
	// (GET /api/workflows)
	ListWorkflows(w http.ResponseWriter, r *http.Request)
	// Get workflow definition
	// (GET /api/workflows/{name}/definition)
	GetWorkflowDefinition(w http.ResponseWriter, r *http.Request, name string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List workflow run history
// (GET /api/history)
func (_ Unimplemented) GetHistory(w http.ResponseWriter, r *http.Request, params GetHistoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get specific workflow run details
// (GET /api/history/{id})
func (_ Unimplemented) GetHistoryRun(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a workflow
// (POST /api/run)
func (_ Unimplemented) RunWorkflow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current database path
// (GET /api/settings/db-path)
func (_ Unimplemented) GetDBPath(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update database path
// (PUT /api/settings/db-path)
func (_ Unimplemented) SetDBPath(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current log level
// (GET /api/settings/log-level)
func (_ Unimplemented) GetLogLevel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set log level
// (POST /api/settings/log-level)
func (_ Unimplemented) SetLogLevel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current workflow status
// (GET /api/status)
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop the running workflow
// (POST /api/stop)
func (_ Unimplemented) StopWorkflow(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List available workflows
// (GET /api/workflows)
func (_ Unimplemented) ListWorkflows(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get workflow definition
// (GET /api/workflows/{name}/definition)
func (_ Unimplemented) GetWorkflowDefinition(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHistory operation middleware
func (siw *ServerInterfaceWrapper) GetHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "workflow_path" -------------

	err = runtime.BindQueryParameter("form", true, false, "workflow_path", r.URL.Query(), &params.WorkflowPath)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workflow_path", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHistoryRun operation middleware
func (siw *ServerInterfaceWrapper) GetHistoryRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHistoryRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunWorkflow operation middleware
func (siw *ServerInterfaceWrapper) RunWorkflow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunWorkflow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDBPath operation middleware
func (siw *ServerInterfaceWrapper) GetDBPath(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDBPath(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetDBPath operation middleware
func (siw *ServerInterfaceWrapper) SetDBPath(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetDBPath(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) GetLogLevel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogLevel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetLogLevel operation middleware
func (siw *ServerInterfaceWrapper) SetLogLevel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetLogLevel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopWorkflow operation middleware
func (siw *ServerInterfaceWrapper) StopWorkflow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopWorkflow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWorkflows operation middleware
func (siw *ServerInterfaceWrapper) ListWorkflows(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkflows(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflowDefinition operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflowDefinition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflowDefinition(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/history", wrapper.GetHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/history/{id}", wrapper.GetHistoryRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/run", wrapper.RunWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/settings/db-path", wrapper.GetDBPath)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/settings/db-path", wrapper.SetDBPath)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/settings/log-level", wrapper.GetLogLevel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/settings/log-level", wrapper.SetLogLevel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/status", wrapper.GetStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/stop", wrapper.StopWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/workflows", wrapper.ListWorkflows)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/workflows/{name}/definition", wrapper.GetWorkflowDefinition)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYW2/bNhT+KwQ3YC3g1N7aDpjf0gXtPGRtEKPIw1YUtHhkM6VIlhenRuD/PpC6WLJI",
	"R26cYU9xxCOew+/7zkW8x5kslBQgrMHTe2yyFRQk/Lx4c0Xs6hq+OjDWP1BaKtCWQVhWxK78X7tRgKfY",
	"WM3EEm+3o/qJXNxCZvF21OxklBQGHrcVM2TBgc4tqP5GzEIxExS+tXZjwsIStH/ZWFDJ5Zi3S7m8hDXw",
	"JAjcrw4M/er6hjD7YQ1aMxpBYQWEvtFEZDEsRg+dTd4J0NEXleR8DpmJv6f0e1csOq+2VjUoGd30jjD7",
	"Vuqjjj63xEbODYICPQ/g5lIXxOIppsTCmWUF4FHfN2gt40d9AMKVLfhHzaNrghQQXTgA7PdBZyzR9rgT",
	"G0usM9HdLLMcTkER0YRz4O+0dCrBVBKjA/H5nGtyM/z4UUOOp/iH8a7yjKuyM/ZpXTrfxUi0Jpt40NdO",
	"JFOTtirF8AA69aUXwwgzoVxZKQmlzDIpCL/q+O0ztB+10u1CMDy2vQISie5O6i85l3cDOZ8H2tJ1WTsh",
	"/Mu73RZSciBi39ehqG8qu4rWeByQktzCMU53aUbBZJopjzue4j9BfGHCoGCERLBCGVHWaaCI5BY0sitA",
	"t3KBfGQcLJhdfrWSNeyQKg3pesOEsURk8aS4lYvjKo0G47g9NsGcATo7XpVdJGuSUKlvpCEHDSIDihYb",
	"ZFfMIJ/IPxmkiCaFQc++wAad/eMmk5eANBjJ10DRmnAHz3GP4hjptcuZyGWkKSQxT8KXmCJGeE04ozER",
	"HwzLQpHQJDNlJsbzgpm6lMbXVWv1YLb3C3JTO4ZViuYlUw1LAyvvIViunegDkkmRs+VnI4gyKxlXMAj6",
	"ObS3wU2v5KyxZcL++iqavKeoyaEpHxnggaSsi+PnpFobiyOG324p7evyBDg0jWhQR+onS6QpHT819APb",
	"BprLQtGtXOdXM5RLjepe8NZXsQtiVgtJNMXNgIQ7BudXMzzCa9Cm3OXnF5MXkzDtKRBEMTzFL8OjsqyE",
	"IMdEsfGKGSv1xv+/hKB0jy/xwcwonuJ3YP+oTMpUL8CCNnj6937gf5FvrHBF3bZkjsr6b5CVSIN1WmB/",
	"aDzFXx2E/UokMWcFs3hUfauVkOQktI7Xk1Hkw2bf9Yc8N2ADbIosmQjhJ5zJYBv3NsjZW8Z9H15sUC15",
	"FCQfd9dNi7bXnkbSjkphoWfV/DJCxmUZGDNCOWEc6AgZK5UC+jwRRaXMQ+4/hX4dBqegjl8mk6oUWhBB",
	"GEQpzrKA7fjWSLH7vD46v3zV7Q/EvS5+yYz1QmqA1k4Y/+LrMriu9Rz0GjQqO63fzLiiIF7b5UbtXVCt",
	"e2/XToTxPaPbAdngT/BAQty0/c0uamoqIVTMMJ/SGr46poHiqdUOIizt5PhYmgazs03PVP48FCxhPJDx",
	"avKqT0bHWEifnE7Q7+HuHVhkFGQsZ1mXwyaGmkNdNXNpItxdO1EHVUEOxr6RdHMy/FpfbwG+Lq3bRzLX",
	"7Y1H9poEOdWne8lihJaZCLMm0vWxvN1vB9gmXAOhG1R/aXWpnHt3iDQs7pgzYC0TSzOmi7N6gEhlYHn7",
	"hp8wEfbu9yII/u60BmERJZYsiIGyBXynurPUZspFEJh3EDi9irvXpE8g5Mchf9EGCTnlJ9qjBHwsQx+D",
	"i31yesLlcnnW3J6mpFvfv+KT1oLhl7ZpIXO5ROU+aX22bEaJIjvfO+Pp5bl/hf3klfYx6F7WiCE/cz4k",
	"0hQHc9jnp5Re0wJScpvXY9+T5evejdsBgVXRptV112pKtWV1TqnSbX1uper09f9diw2TeXJQei87Q020",
	"a0oVrv2q5Uj7rJ+k1eAn4JvG6r+c9cN92IBh/xzxvXHfxKZ4siaMkwWHPbMuDuN7P19vxxRyJljpIZ0n",
	"dagXO+sHZnsQmaRAyyYkNfLefOieprudGiMDf/gzYOQ/2YfZMXfZaRm3gHxw5G+N+71sv4ttGMxCBy6x",
	"dprjKR7j7aftvwEAAP//41e8OtAdAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
